### ISSUE TITLE
Use the new one here: https://github.com/ThatTSGuy/discord-qr-token-grabber

### ISSUE THREAD

**Issue by 4MAANR** [verlox/Discord-QR-Token-Logger#6]
Use the new one here: https://github.com/ThatTSGuy/discord-qr-token-grabber

**Comment by verlox** [comment]
dont bring ur shit logger here kid

**Comment by russianheavy1337** [comment]
stfu u skid

**Comment by ThatTSGuy** [comment]
> dont bring ur shit logger here kid

Dude, your logger is garbage. Your literally web scraping the credentials which makes it memory intensive, slow, and just janky. As soon as Discord updates their website all your hardcoded queries go down the drain.

**Comment by ThatTSGuy** [comment]
> stfu u skid

Says the skid on a token logger repo

**Comment by verlox** [comment]
> > dont bring ur shit logger here kid
> 
> 
> 
> Dude, your logger is garbage. Your literally web scraping the credentials which makes it memory intensive, slow, and just janky. As soon as Discord updates their website all your hardcoded queries go down the drain.

i made it in like 15 minutes and anyways you had to advertise on existing code just to promote it, try harder retard

**Comment by russianheavy1337** [comment]
shut the fuck up skid no one cares about your shitty node qr logger

**Comment by ThatTSGuy** [comment]
> shut the fuck up skid no one cares about your shitty node qr logger

Do you know the definition of skid? You should as you personify it perfectly.

Skid, short for script kiddie, is a person who uses existing computer scripts or code to hack into computers, lacking the expertise to write their own.

**Comment by ThatTSGuy** [comment]
> > > dont bring ur shit logger here kid
> > 
> > 
> > Dude, your logger is garbage. Your literally web scraping the credentials which makes it memory intensive, slow, and just janky. As soon as Discord updates their website all your hardcoded queries go down the drain.
> 
> i made it in like 15 minutes and anyways you had to advertise on existing code just to promote it, try harder retard

Your 36 commits a across multiple months disprove your statement that it took you "15 minutes." You clearly agree with me on the fact that your code is poorly thought out and lacks ingenuity. The whole "retard" insult and the poor code just means your lacking in the brain department :)

**Comment by verlox** [comment]
if im supposedly lacking in the brain department, but you require to comment on a total of 3 diff repos to advertise yours, you must just be desperate. clearly, i do not try to make gui apps often, and i am quite good at replicating web requests. if i really cared, i wouldve improved the idea. the idea is quite dead tho, since everyone is aware of it. also, nice fucking profile readme, no one gives a shit that you support ukraine. you also have little contributions, so i can tell you really dont bother, and put in effort. so please, keep trying to talk to me about how im supposedly braindead, when you are picking sides in a war you will never see or be near, or when you rely on other peoples work to advertise in.
